function [fitresult, gof] = createFit(x, log_log_y, log_y)
%CREATEFIT1(X,LOG_LOG_Y,LOG_Y)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : x
%      Y Output: log_log_y
%      Weights : log_y
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 29-Jul-2021 14:00:56


%% Fit: 'untitled fit 1'.
[xData, yData, weights] = prepareCurveData( x, log_log_y, log_y );

% Set up fittype and options.
ft = fittype( 'poly1' );
opts = fitoptions( 'Method', 'LinearLeastSquares' );
opts.Weights = weights;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure();
h = plot( fitresult, xData, yData );
legend( h, 'log_log_y vs. x with log_y', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'x', 'Interpreter', 'none' );
ylabel( 'log_log_y', 'Interpreter', 'none' );
grid on


